apiVersion: v1
kind: Service
metadata:
  name: mehmet-service
  namespace: mehmet
spec:
  selector:
    app: my-dockerhub-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  
  type: NodePort

