apiVersion: v1
kind: Service
metadata:
  name: mehmet-service
spec:
  selector:
    app: my-dockerhub-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Port numarasını 30000 olarak ayarlıyoruz, isteğe göre değiştirilebilir
  type: NodePort

